# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bill Murphy
tagline:             'Data Science, Machine Learning, Programming Languages, and Finance'
url:                 http://billpmurphy.github.io
shorturl:            billpmurphy.github.io
paginate:            1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

markdown:            redcarpet
redcarpet:
  extensions:        ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# About/contact
author:
  name:              Bill Murphy
  url:               https://github.com/billpmurphy
  email:             billpmurphy92@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/billpmurphy/billpmurphy.github.io

pages_list:
  CV:     '/resume.pdf'
  GitHub: 'http://github.com/billpmurphy/'
  Blog:   '/blog/'
